apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - namespace.yaml
  - rmq-secret.yaml
  - services.yaml
  - inventory
  - notification
  - order
  - payment
  - user
