version: '3.3'

services:
  order:
    image: order
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # GRPC API port
    environment:
      ORDER_DB_HOST: inventory-db
      ORDER_DB_PORT: 3311
      ORDER_DB_NAME: inventory
      ORDER_DB_USER: inventory
      ORDER_DB_PASSWORD: ${DB_PASSWORD}
      ORDER_DB_MAX_CONN: 5
    depends_on:
      - order-db
    restart: unless-stopped

  order-db:
    image: percona:8.0
    container_name: inventory-db
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - inventory-db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  order-db-data:
