global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "user"
    static_configs:
      - targets:
          - "user:8082"
          - "user-workflow-worker:8082"
          - "user-message-handler:8082"
    metrics_path: /metrics

  - job_name: "temporal"
    static_configs:
      - targets:
          - "user-temporal:8000"
    metrics_path: /metrics
