services:
  payment:
    container_name: payment
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      USER_DATABASE_HOST: payment-db
      USER_DATABASE_NAME: payment
      USER_DATABASE_USER: payment
      USER_DATABASE_PASSWORD: 1234
    depends_on:
      payment-db:
        condition: service_healthy

  payment-message-handler:
    container_name: payment-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: payment-db
      USER_DATABASE_NAME: payment
      USER_DATABASE_USER: payment
      USER_DATABASE_PASSWORD: 1234

      USER_AMQP_HOST: payment-rmq
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest

      USER_TEMPORAL_HOST: payment-temporal:7234
    depends_on:
      payment-db:
        condition: service_healthy
      payment-rmq:
        condition: service_healthy

  payment-db:
    image: "mysql:8.3"
    container_name: payment-db
    command: [ "--max_connections=100" ]
    volumes:
      - "payment-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3307"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  payment-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: payment-rmq
    hostname: payment-rmq
    ports:
      - "15672:15672"
    volumes:
      - "payment-rmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  payment-db-data:
  payment-rmq-data:
  payment-grafana-data:
