global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order'
    static_configs:
      - targets: ['order:8082', 'order-message-handler:8082']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:8082', 'payment-message-handler:8082']

  - job_name: 'product'
    static_configs:
      - targets: ['product:8082', 'product-message-handler:8082']

  - job_name: 'user'
    static_configs:
      - targets: ['user:8082', 'user-message-handler:8082']

  - job_name: 'notification'
    static_configs:
      - targets: ['notification:8082', 'notification-message-handler:8082']