version: '3.3'

services:
  inventory:
    image: inventory
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # GRPC API port
    environment:
      INVENTORY_DB_HOST: inventory-db
      INVENTORY_DB_PORT: 3311
      INVENTORY_DB_NAME: inventory
      INVENTORY_DB_USER: inventory
      INVENTORY_DB_PASSWORD: 1234
      INVENTORY_DB_MAX_CONN: 5
    depends_on:
      - inventory-db
    restart: unless-stopped

  inventory-db:
    image: percona:8.0
    container_name: inventory-db
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3311:3311"
    volumes:
      - inventory-db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  inventory-db-data:
