services:
  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      USER_DATABASE_HOST: inventory-db
      USER_DATABASE_NAME: inventory
      USER_DATABASE_USER: inventory
      USER_DATABASE_PASSWORD: 1234
    depends_on:
      inventory-db:
        condition: service_healthy

  inventory-message-handler:
    container_name: inventory-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: inventory-db
      USER_DATABASE_NAME: inventory
      USER_DATABASE_USER: inventory
      USER_DATABASE_PASSWORD: 1234

      USER_AMQP_HOST: inventory-rmq
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest

      USER_TEMPORAL_HOST: inventory-temporal:7234
    depends_on:
      inventory-db:
        condition: service_healthy
      inventory-rmq:
        condition: service_healthy

  inventory-db:
    image: "mysql:8.3"
    container_name: inventory-db
    command: [ "--max_connections=100" ]
    volumes:
      - "inventory-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3307"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  inventory-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: inventory-rmq
    hostname: inventory-rmq
    ports:
      - "15672:15672"
    volumes:
      - "inventory-rmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

  inventory-grafana:
    image: grafana/grafana:11.1.4
    container_name: inventory-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - inventory-grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  inventory-db-data:
  inventory-rmq-data:
  inventory-grafana-data:
