apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      name: order-api
      labels:
        app: order-api
    spec:
      initContainers:
        - name: order-migrator
          image: rp-order:latest
          imagePullPolicy: Never
          command:
            - /app/order
          args:
            - migrate
          env:
            - name: ORDER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: ORDER_DATABASE_NAME
              value: order
            - name: ORDER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: order-database-access
                  key: ORDER_DATABASE_USER
            - name: ORDER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-database-access
                  key: ORDER_DATABASE_PASSWORD
      containers:
        - name: order-api
          image: rp-order:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/order
          args:
            - service
          env:
            - name: ORDER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: ORDER_DATABASE_NAME
              value: order
            - name: ORDER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: order-database-access
                  key: ORDER_DATABASE_USER
            - name: ORDER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-database-access
                  key: ORDER_DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      