apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-temporal
  labels:
    app: user-temporal
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-temporal
  template:
    metadata:
      name: user-temporal
      labels:
        app: user-temporal
    spec:
      initContainers:
        - name: user-migrator
          image: rp-user:latest
          imagePullPolicy: Never
          command:
            - /app/user
          args:
            - migrate
          env:
            - name: USER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: USER_DATABASE_NAME
              value: user
            - name: USER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_USER
            - name: USER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_PASSWORD
      containers:
        - name: user-temporal
          image: rp-user:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/user
          args:
            - workflow-worker
          env:
            - name: USER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: USER_DATABASE_NAME
              value: user
            - name: USER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_USER
            - name: USER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_PASSWORD
            - name: USER_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233
          ports:
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      