apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
  labels:
    app: notification-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      name: notification-api
      labels:
        app: notification-api
    spec:
      initContainers:
        - name: notification-migrator
          image: rp-notification:latest
          imagePullPolicy: Never
          command:
            - /app/notification
          args:
            - migrate
          env:
            - name: NOTIFICATION_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: NOTIFICATION_DATABASE_NAME
              value: notification
            - name: NOTIFICATION_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_USER
            - name: NOTIFICATION_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_PASSWORD
      containers:
        - name: notification-api
          image: rp-notification:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/notification
          args:
            - service
          env:
            - name: NOTIFICATION_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: NOTIFICATION_DATABASE_NAME
              value: notification
            - name: NOTIFICATION_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_USER
            - name: NOTIFICATION_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      