apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-message-handler
  labels:
    app: inventory-message-handler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inventory-message-handler
  template:
    metadata:
      name: inventory-message-handler
      labels:
        app: inventory-message-handler
    spec:
      initContainers:
        - name: inventory-migrator
          image: rp-inventory:latest
          imagePullPolicy: Never
          command:
            - /app/inventory
          args:
            - migrate
          env:
            - name: INVENTORY_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: INVENTORY_DATABASE_NAME
              value: inventory
            - name: INVENTORY_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_USER
            - name: INVENTORY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_PASSWORD
      containers:
        - name: inventory-message-handler
          image: rp-inventory:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/inventory
          args:
            - message-handler
          env:
            - name: INVENTORY_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: INVENTORY_DATABASE_NAME
              value: inventory
            - name: INVENTORY_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_USER
            - name: INVENTORY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_PASSWORD
            - name: INVENTORY_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:5672
            - name: INVENTORY_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: INVENTORY_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      