apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  labels:
    app: inventory-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      name: inventory-api
      labels:
        app: inventory-api
    spec:
      initContainers:
        - name: inventory-migrator
          image: rp-inventory:latest
          imagePullPolicy: Never
          command:
            - /app/inventory
          args:
            - migrate
          env:
            - name: INVENTORY_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: INVENTORY_DATABASE_NAME
              value: inventory
            - name: INVENTORY_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_USER
            - name: INVENTORY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_PASSWORD
      containers:
        - name: inventory-api
          image: rp-inventory:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/inventory
          args:
            - service
          env:
            - name: INVENTORY_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: INVENTORY_DATABASE_NAME
              value: inventory
            - name: INVENTORY_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_USER
            - name: INVENTORY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-database-access
                  key: INVENTORY_DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      