services:
  user:
    image: user
    container_name: user
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      USER_DATABASE_HOST: user-db
      USER_DATABASE_NAME: user
      USER_DATABASE_USER: user
      USER_DATABASE_PASSWORD: 1234
    depends_on:
      user-db:
        condition: service_healthy

  user-message-handler:
    image: user
    container_name: user-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: user-db
      USER_DATABASE_NAME: user
      USER_DATABASE_USER: user
      USER_DATABASE_PASSWORD: 1234

      USER_AMQP_HOST: user-rmq
      USER_AMQP_PORT: 5672
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest
    depends_on:
      user-db:
        condition: service_healthy
      user-rmq:
        condition: service_healthy

  user-db:
    image: "mysql:8.3"
    container_name: user-db
    command: [ "--max_connections=100" ]
    volumes:
      - "user-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  user-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: user-rmq
    hostname: user-rmq
    ports:
      - "15672:15672"
    volumes:
      - "user-rmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  user-db-data:
  user-rmq-data: