apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  labels:
    app: payment-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      name: payment-api
      labels:
        app: payment-api
    spec:
      initContainers:
        - name: payment-migrator
          image: rp-payment:latest
          imagePullPolicy: Never
          command:
            - /app/payment
          args:
            - migrate
          env:
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              value: payment
            - name: PAYMENT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: payment-database-access
                  key: PAYMENT_DATABASE_USER
            - name: PAYMENT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-database-access
                  key: PAYMENT_DATABASE_PASSWORD
      containers:
        - name: payment-api
          image: rp-payment:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/payment
          args:
            - service
          env:
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              value: payment
            - name: PAYMENT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: payment-database-access
                  key: PAYMENT_DATABASE_USER
            - name: PAYMENT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-database-access
                  key: PAYMENT_DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      