name: Go Microservices Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-user:
    name: Test User Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Tidy dependencies for order
      run: |
        cd user
        go mod tidy

    - name: Run tests for order
      run: |
        cd user
        go test ./pkg/... -v -race -coverprofile=coverage.out

  test-inventory:
    name: Test Inventory Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Tidy dependencies for notification
      run: |
        cd inventory
        go mod tidy

    - name: Run tests for notification
      run: |
        cd inventory
        go test ./pkg/... -v -race -coverprofile=coverage.out

  test-order:
    name: Test Order Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Tidy dependencies for order
        run: |
          cd order
          go mod tidy

      - name: Run tests for order
        run: |
          cd order
          go test ./pkg/... -v -race -coverprofile=coverage.out

  test-notification:
    name: Test Notification Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Tidy dependencies for notification
        run: |
          cd notification
          go mod tidy

      - name: Run tests for notification
        run: |
          cd notification
          go test ./pkg/... -v -race -coverprofile=coverage.out

  test-payment:
    name: Test Payment Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Tidy dependencies for payment
        run: |
          cd payment
          go mod tidy

      - name: Run tests for payment
        run: |
          cd payment
          go test ./pkg/... -v -race -coverprofile=coverage.out
